name: Setup Environment Variables
description: Set up the txtx .env file.

inputs:
  infura_api_key:
    description: 'The Infura API key'
    required: true
  nhost_region:
    description: 'The nhost region'
    required: true
  nhost_subdomain:
    description: 'The nhost subdomain'
    required: true
    
runs:
  using: 'composite'
  steps:
    - run: |
        touch .env
        echo RELAYER_BASE_URL="https://txtx.link" >> .env
        echo RELAYER_HOST="txtx.link" >> .env
        echo INFURA_API_KEY="${{ inputs.INFURA_API_KEY }}" >> .env
        echo AUTH_SERVICE_URL="https://id.txtx.run" >> .env
        echo NHOST_REGION="${{ inputs.NHOST_REGION }}" >> .env
        echo NHOST_SUBDOMAIN="${{ inputs.NHOST_SUBDOMAIN }}" >> .env
        echo TXTX_CONSOLE_URL="https://txtx.run" >> .env
        cat .env
      shell: bash
