name: Setup Environment Variables
description: Set up the txtx .env file.

inputs:
  working_directory:
    description: 'Optional working directory where .env should be created'
    required: false
    default: '.'
    
runs:
  using: 'composite'
  steps:
    - run: |
        touch "${{ inputs.working_directory }}/.env"
        echo AUTH_SERVICE_URL="https://id.txtx.run/v1" >> "${{ inputs.working_directory }}/.env"
        echo TXTX_CONSOLE_URL="https://txtx.run" >> "${{ inputs.working_directory }}/.env"
      shell: bash
